### ISSUE TITLE
Criar interface de Avaliação

### ISSUE THREAD

**Issue by bruno743** [ES2-UFPI/Grupo6#54]

**Comment by heldersrvio** [comment]
Commits do dia 21 de junho de 2021 (no branch helder#54):

- commit ce77b8b04eeaf07a05a2055d3e81b92c0278124b
- commit 219b4c00b98287a1395e7e6bad423d2d0928d5d3
- commit 2310144b19aa934088408109c2ec9c09f57e18d8
- commit c858d80551bea8f59a93af6c9a51a3a9756de05a
- commit e31136ab9305e419002024c594774a5c237808f3
- commit 20e5c3d206f3902a94a762bbba8cfc91a89c50c1
